repos:
- repo: local
  hooks:
  - id: lint
    name: lint
    language: system
    entry: make
    args: [lint]
    types: [python]
  - id: format
    name: format
    language: system
    entry: make
    args: [format]
    types: [python]
