language: python
python:
  - "3.7"
  - "3.8"
env:
  - VENV_PYTHON="/usr/bin/env python"
install:
  - pip install -Ur requirements.txt
  - pip install python-coveralls
  - pip install -U coverage>=4.4
script:
  - make lint
  - make test
after_success:
  - coveralls
