language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install -U coverage>=4.4
script:
  - make lint
  - make test
after_success:
  - coveralls
